CREATE TABLE usuario(
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(300) NOT NULL,
    papel VARCHAR(20) NOT NULL CHECK(papel IN ('MEDICA', 'ASSISTENTE')),
    email VARCHAR(254) UNIQUE NOT NULL,
    senha_hash VARCHAR(255) NOT NULL
);

CREATE TABLE paciente(
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(300) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    email VARCHAR(254),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);